### ISSUE TITLE
RDAP support?

### ISSUE THREAD

**Issue by notpushkin** [pogzyb/asyncwhois#27]
https://rdap.org/ :-)

**Comment by pogzyb** [comment]
Thanks for the suggestion. 

Yes, I have plans to include some RDAP functionality soon. I've got a decent chunk of code that currently supports domain look ups, but other features like searching IPs or CIDRs might be out of scope for me alone at this time. Also, I was debating releasing it as a separate project/repository, but seeing how this project is starting to get more traction, it may be best to just stuff it all in here.

If you're interested, I can include you on the PR for the domain query and parsing via RDAP. Should be able to get it out in a week or so.

**Comment by pogzyb** [comment]
@notpushkin 

https://github.com/pogzyb/whodap 👀

I decided to release the RDAP stuff as its own project, but I still plan to add hooks for a few of these "whodap" methods into this repository as well. I will need a few more days to get to those hooks added here. I hope the other project helps you in the meantime though.
