### ISSUE TITLE
Remove asynctest

### ISSUE THREAD

**Issue by fabaff** [pogzyb/asyncwhois#46]
`asynctest` is no longer maintained and doesn't work with Python 3.11

https://github.com/Martiusweb/asynctest/issues/163

**Comment by fabaff** [comment]
Thanks

**Comment by fabaff** [comment]
Could you please publish a new release? Would help all distributions as they wouldn't have to grab the changes from #47.

Thanks again.

**Comment by pogzyb** [comment]
@fabaff no problem! v1.0.2 is released.
