### ISSUE TITLE
.org domains

### ISSUE THREAD

**Issue by menshatov** [pogzyb/asyncwhois#67]
Hi, I've got a strange error when try to get whois of .org domains:
result = asyncwhois.whois_domain('iana.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
socket.gaierror: [Errno 11001] getaddrinfo failed

result = asyncwhois.whois_domain('domain.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
socket.gaierror: [Errno 11001] getaddrinfo failed

result = asyncwhois.whois_domain('nlmk.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by pogzyb** [comment]
Thanks for finding this! I'm surprised this hasn't been raised before. I found the underlying issue, made some modifications to handle these scenarios, and tested with the domains you mentioned. I want to test a bit more, but should get a release out sometime later today or tomorrow the latest with these changes.

**Comment by pogzyb** [comment]
This should be handled in v1.0.9. Please let me know if the error persists or if you find any other bugs. Thanks again.
