### ISSUE TITLE
can not successfully run demo in readme 

### ISSUE THREAD

**Issue by dingonet1** [pogzyb/asyncwhois#77]
Hi,
  I can not successfully got demain information as demoed in README.
  I use version 1.0.10 with python3.8.When I check in code I found  aio_whois_domian is the method to use with async .But this function return DomainLookup instance.And I  cannot find how to got domain expiretime and other information ,can any one help me on this issue?

**Comment by dingonet1** [comment]
sorry,I missed something!

**Comment by pogzyb** [comment]
Hi, asyncwhois version 1.1.0 requires python>=3.9. For python 3.8 use asyncwhois versions 1.0.X
